Update Jenkinsfile_AIP

diff --git a/Jenkinsfile_AIP b/Jenkinsfile_AIP
--- a/Jenkinsfile_AIP
+++ b/Jenkinsfile_AIP
@@ -107,7 +107,11 @@ spec:
 								echo 'Remove the 3 lines below when we switch to the actual EJB repo'
 								// sh "mv sample-java-app/target/sample-0.0.1-SNAPSHOT.jar sample-java-app/target/EJB_build-${BUILD_NUMBER}_branch-${env.GIT_BRANCH}.jar"
 								sh 'ls -lrt sample-java-app/target/'
-								sh "mvn -X deploy:deploy-file  -Dfile=sample-java-app/target/sample-EJB-build-branch.jar -DpomFile=sample-java-app/pom.xml -DrepositoryId=snapshots -Durl=https://archiva.sgn.devops.accentureanalytics.com/repository/snapshots/"
+								ARTIFACT=EJB_build-${BUILD_NUMBER}_branch-${env.GIT_BRANCH}
+								dir("sample-java-app/target") {
+									sh "mvn -X deploy:deploy-file  -Dfile=$ARTIFACT.jar -DpomFile=sample-java-app/pom.xml -DrepositoryId=snapshots -Durl=https://archiva.sgn.devops.accentureanalytics.com/repository/snapshots/"
+								}
+								//sh "mvn -X deploy:deploy-file  -Dfile=sample-java-app/target/sample-EJB-build-branch.jar -DpomFile=sample-java-app/pom.xml -DrepositoryId=snapshots -Durl=https://archiva.sgn.devops.accentureanalytics.com/repository/snapshots/"
 							}
 					}
 				}
@@ -131,7 +135,6 @@ spec:
 									USERNAME=env.USERNAME_RELEASE_DEPLOY
 									HOSTS=env.HOSTS_RELEASE_DEPLOY
 								}
-								echo HOSTS
 								HOSTS.tokenize(',').each { HOSTNAME ->
 									echo 'I am deploying the artifact into the target environment ${HOSTNAME} as user ${USERNAME}'
 									echo 'Replace all the lines below for EJB and add the parameters to propfile and make refrences below'
@@ -167,43 +170,43 @@ spec:
 					steps {
 						container('gradle') {
 							script {
-									withMaven(maven: 'MAVEN-3.6.3') {
-										echo "I am executing Smoke Test on target dev environment post deployment"
-										/*RESP=`curl -X GET "${bamboo.uri}/RequestsRunning" -H "accept: application/xml" -H "authorization: bearer lR0AA2qfq7v9Ry96vDAgqcer1GPVd5yStmv1_aJVFS43rk06EytB7WsS0_owoiXIgpOXmZVEfkY4ST0JwHtRBk7RH0QRaldWtQT8udC0VdimdGx38RddY2sGaeeF0t9Aflr5rh1Jc_EUfkNK8YrKVxQ6kxB05aCe46CD2fkognv7TiJATmht-ycUjEsd_oy8jH5EK9fmn9eL-wXavNTQcEdsUmFm3-2r3IJDzMK7XCa74qu353yOKLvVyZ1yYQBnc1_fY5GS1BDrFLUZprxpAS30lGEu-d_JTTOQ989UJtIEB3cZzDkIQzeqdYBGCsiDdjdHo2DC1FK2kVPyBITTbQ"`
-										echo "The response for current execution status is: $RESP"
-										if [ "$RESP" != "[]" ];
-										then
-										echo "There is a test executing currently in Worksoft. Hence, not proceeding with the execution of Worksoft test cases."
-										exit 1
-										else
-										echo "There are no tests executing right now. Hence, proceeding with Worksoft test execution"
-										fi
-										# To abort the request before attempting to re-run, uncomment and run below line.
-										# abort=$(curl -X PUT -H "Authorization: Bearer $token" -d "" -H "id: ${bamboo.RequestID}" ${bamboo.uri}/Request/${bamboo.RequestID}/abort/)
-										guid=$(curl -X PUT -H "Authorization: Bearer $token" -d "" -H "parameters: {TestEnv}{${bamboo.stage_name}}" -H "id: ${bamboo.RequestID}" ${bamboo.uri}/ExecuteRequest/ | tr -d \")
-										echo "The GUID is: $guid"
-										status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/ | awk -F':' '{print $2}' | tr -d \" | tr -d \})
-										echo "The status is: $status"
-										while [[ $status != *"Completed"* ]]
-										do
-										status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/ | awk -F':' '{print $2}' | tr -d \" | tr -d \})
-										echo "The status is: $status"
-										sleep 15
-										done
-										status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/)
-										echo "The status is: $status"
-										execstatus=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/ | awk -F':' '{print $3}' | tr -d \" | tr -d \})
-										echo "The exec status is: $execstatus"
-										if [[ $execstatus != *Passed* ]];
-										then
-										echo "Failed"
-										exit 1
-										else
-										echo "Passed"
-										exit
-										fi
-										exit */
-									}
+								withMaven(maven: 'MAVEN-3.6.3') {
+									echo "I am executing Smoke Test on target dev environment post deployment"
+									/*RESP=`curl -X GET "${bamboo.uri}/RequestsRunning" -H "accept: application/xml" -H "authorization: bearer lR0AA2qfq7v9Ry96vDAgqcer1GPVd5yStmv1_aJVFS43rk06EytB7WsS0_owoiXIgpOXmZVEfkY4ST0JwHtRBk7RH0QRaldWtQT8udC0VdimdGx38RddY2sGaeeF0t9Aflr5rh1Jc_EUfkNK8YrKVxQ6kxB05aCe46CD2fkognv7TiJATmht-ycUjEsd_oy8jH5EK9fmn9eL-wXavNTQcEdsUmFm3-2r3IJDzMK7XCa74qu353yOKLvVyZ1yYQBnc1_fY5GS1BDrFLUZprxpAS30lGEu-d_JTTOQ989UJtIEB3cZzDkIQzeqdYBGCsiDdjdHo2DC1FK2kVPyBITTbQ"`
+									echo "The response for current execution status is: $RESP"
+									if [ "$RESP" != "[]" ];
+									then
+									echo "There is a test executing currently in Worksoft. Hence, not proceeding with the execution of Worksoft test cases."
+									exit 1
+									else
+									echo "There are no tests executing right now. Hence, proceeding with Worksoft test execution"
+									fi
+									# To abort the request before attempting to re-run, uncomment and run below line.
+									# abort=$(curl -X PUT -H "Authorization: Bearer $token" -d "" -H "id: ${bamboo.RequestID}" ${bamboo.uri}/Request/${bamboo.RequestID}/abort/)
+									guid=$(curl -X PUT -H "Authorization: Bearer $token" -d "" -H "parameters: {TestEnv}{${bamboo.stage_name}}" -H "id: ${bamboo.RequestID}" ${bamboo.uri}/ExecuteRequest/ | tr -d \")
+									echo "The GUID is: $guid"
+									status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/ | awk -F':' '{print $2}' | tr -d \" | tr -d \})
+									echo "The status is: $status"
+									while [[ $status != *"Completed"* ]]
+									do
+									status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/ | awk -F':' '{print $2}' | tr -d \" | tr -d \})
+									echo "The status is: $status"
+									sleep 15
+									done
+									status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/)
+									echo "The status is: $status"
+									execstatus=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/ | awk -F':' '{print $3}' | tr -d \" | tr -d \})
+									echo "The exec status is: $execstatus"
+									if [[ $execstatus != *Passed* ]];
+									then
+									echo "Failed"
+									exit 1
+									else
+									echo "Passed"
+									exit
+									fi
+									exit */
+								}
 							}
 						}
 					}
