Update Jenkinsfile_AIP

diff --git a/Jenkinsfile_AIP b/Jenkinsfile_AIP
--- a/Jenkinsfile_AIP
+++ b/Jenkinsfile_AIP
@@ -40,6 +40,7 @@ spec:
 		HOSTS_DEV_DEPLOY="10.6.74.91, 10.6.74.92"
 		USERNAME_RELEASE='wasadmin'
 		HOSTS_RELEASE_DEPLOY="10.6.74.93, 10.6.74.94"
+		ARTIFACT="EJB-branch-${env.GIT_BRANCH}-build-${env.BUILD_NUMBER}"
 	}
 	stages {
 		stage('Build & Unit Test') {
@@ -51,7 +52,7 @@ spec:
 							echo 'use the command below when we switch to EJB source'
 							//sh 'gradle --no-daemon clean build'
 							echo 'Add gradle clean and build for EJB and comment this step' 
-							sh 'mvn -f sample-java-app/pom.xml clean package'
+							sh "mvn -Drevision=${ARTIFACT} -f sample-java-app/pom.xml clean package"
 							propfile = readProperties(file: './project.properties')
 							if (propfile['javadoc'] == "true") {
 								sh 'mvn javadoc:aggregate'
@@ -94,21 +95,21 @@ spec:
 			steps {
 				container('gradle') {
 					script {
-							withMaven(maven: 'MAVEN-3.6.3') {
-								echo 'I am pushing the artifact with unique name showing the branch from which it is generated, to Archiva'
-								echo 'Replace the next 4 lines to reflect the EJB artifact and push it to archiva'
-								echo 'Use the 5 lines below when we switch to the actual EJB repo' 
-								/* echo 'copying the jar and war files from the individual target directories and copying it to artifacts directory '
-								sh "mkdir -p $WORKSPACE/artifacts"
-								sh "cp /dist/libs/* $WORKSPACE/artifacts/" 
-								echo 'create a tar file on the Jenkins server'
-								sh "cd $WORKSPACE/artifacts/ && tar -cvzf artifact.tar * && md5sum artifact.tar archiveArtifacts artifacts: 'artifacts/*.tar', fingerprint: true 
-								*/
-								echo 'Remove the 3 lines below when we switch to the actual EJB repo'
-								sh "mv sample-java-app/target/sample-0.0.1-SNAPSHOT.jar sample-java-app/target/sample-build_${BUILD_NUMBER}-branch_${env.GIT_BRANCH}.jar"
-								sh 'ls -lrt sample-java-app/target/'
-								sh "mvn -X deploy:deploy-file  -Dfile=sample-java-app/target/sample-build_${BUILD_NUMBER}-branch_${env.GIT_BRANCH}.jar -DpomFile=sample-java-app/pom.xml -DrepositoryId=snapshots -Durl=https://archiva.sgn.devops.accentureanalytics.com/repository/snapshots/"
-							}
+						withMaven(maven: 'MAVEN-3.6.3') {
+							echo 'I am pushing the artifact with unique name showing the branch from which it is generated, to Archiva'
+							echo 'Replace the next 4 lines to reflect the EJB artifact and push it to archiva'
+							echo 'Use the 5 lines below when we switch to the actual EJB repo' 
+							/* echo 'copying the jar and war files from the individual target directories and copying it to artifacts directory '
+							sh "mkdir -p $WORKSPACE/artifacts"
+							sh "cp /dist/libs/* $WORKSPACE/artifacts/" 
+							echo 'create a tar file on the Jenkins server'
+							sh "cd $WORKSPACE/artifacts/ && tar -cvzf artifact.tar * && md5sum artifact.tar archiveArtifacts artifacts: 'artifacts/*.tar', fingerprint: true 
+							*/
+							echo 'Remove the 3 lines below when we switch to the actual EJB repo'
+							// sh "mv sample-java-app/target/sample-0.0.1-SNAPSHOT.jar sample-java-app/target/EJB_build-${BUILD_NUMBER}_branch-${env.GIT_BRANCH}.jar"
+							sh 'ls -lrt sample-java-app/target/'
+							sh "mvn -X deploy:deploy-file  -Dfile=sample-java-app/target/sample-${ARTIFACT}.jar -DpomFile=sample-java-app/pom.xml -DrepositoryId=snapshots -Durl=https://archiva.sgn.devops.accentureanalytics.com/repository/snapshots/"
+						}
 					}
 				}
 			}
@@ -118,44 +119,43 @@ spec:
 			steps {
 				container('gradle') {
 					script {
-							withMaven(maven: 'MAVEN-3.6.3') {
-								if (propfile['feature_deploy'] == "true" ) {
-									USERNAME=env.USERNAME_FEATURE_DEPLOY
-									HOSTS=env.HOSTS_FEATURE_DEPLOY
-								}
-								if (env.GIT_BRANCH == 'dev' ) {
-									USERNAME=env.USERNAME_DEV_DEPLOY
-									HOSTS=env.HOSTS_DEV_DEPLOY
-								}
-								if (env.GIT_BRANCH == 'release') {
-									USERNAME=env.USERNAME_RELEASE_DEPLOY
-									HOSTS=env.HOSTS_RELEASE_DEPLOY
-								}
-								echo HOSTS
-								HOSTS.tokenize(',').each { HOSTNAME ->
-									echo 'I am deploying the artifact into the target environment ${HOSTNAME} as user ${USERNAME}'
-									echo 'Replace all the lines below for EJB and add the parameters to propfile and make refrences below'
-									echo 'Accom logic for multiple env and mult servers in each env based on the branch name'
-									echo 'shutting down the tomcat ESB server'
-									/* sh 'ssh ${USERNAME}@${HOSTNAME} "$ESB_BIN_PATH stop || sleep 20"'
-									echo 'force stop any remaining mule process'
-									sh 'ssh ${USERNAME}@${HOSTNAME} "if [[ $(ps aux | grep /opt/mule/latest/ | grep -vc grep)  > 0 ]]; then "kill -9 $(ps -ef|pgrep -f "/opt/mule/latest/bin")"; else echo "do nothing"; fi"' 
-									*/
-									echo 'tomcat server stopped'
-									echo 'copying the tar file from jenkins to deployment directory on app and remove the old folders and untarring the new jar and war files'
-									/* sh 'scp -rp $WORKSPACE/artifacts/artifact.tar $DEPLOYMENT_USER@$DEPOYMENT_SERVER:$DEPLOYMENT_STAGE_DIR/'
-									sh 'ssh ${USERNAME}@${HOSTNAME} "cd $DEPLOYMENT_STAGE_DIR && rm -rf *.war *.jar"'
-									sh 'ssh ${USERNAME}@${HOSTNAME} "cd $DEPLOYMENT_STAGE_DIR && tar -xvzf artifact.tar && rm -rf *.jar"'
-									sh 'ssh ${USERNAME}@${HOSTNAME} "cd $}DEPLOYMENT_DIR} && rm -rf ${ESB_WAR_FOLDERS} && cp -rp ${DEPLOYMENT_STAGE_DIR}/*.war $DEPLOYMENT_DIR"' 
-									*/
-									echo 'Deployment has been completed'
-									echo 'starting the tomcat ESB server'
-									/* sh 'ssh ${USERNAME}@${HOSTNAME} "${ESB_BIN_PATH start}"'
-									sh 'ssh ${USERNAME}@${HOSTNAME} "sleep 20"' 
-									*/
-									echo 'tomcat server started'
-								}
-							}	
+						withMaven(maven: 'MAVEN-3.6.3') {
+							if (propfile['feature_deploy'] == "true" ) {
+								USERNAME=env.USERNAME_FEATURE_DEPLOY
+								HOSTS=env.HOSTS_FEATURE_DEPLOY
+							}
+							if (env.GIT_BRANCH == 'dev' ) {
+								USERNAME=env.USERNAME_DEV_DEPLOY
+								HOSTS=env.HOSTS_DEV_DEPLOY
+							}
+							if (env.GIT_BRANCH == 'release') {
+								USERNAME=env.USERNAME_RELEASE_DEPLOY
+								HOSTS=env.HOSTS_RELEASE_DEPLOY
+							}
+							HOSTS.tokenize(',').each { HOSTNAME ->
+								echo 'I am deploying the artifact into the target environment ${HOSTNAME} as user ${USERNAME}'
+								echo 'Replace all the lines below for EJB and add the parameters to propfile and make refrences below'
+								echo 'Accom logic for multiple env and mult servers in each env based on the branch name'
+								echo 'shutting down the tomcat ESB server'
+								/* sh 'ssh ${USERNAME}@${HOSTNAME} "$ESB_BIN_PATH stop || sleep 20"'
+								echo 'force stop any remaining mule process'
+								sh 'ssh ${USERNAME}@${HOSTNAME} "if [[ $(ps aux | grep /opt/mule/latest/ | grep -vc grep)  > 0 ]]; then "kill -9 $(ps -ef|pgrep -f "/opt/mule/latest/bin")"; else echo "do nothing"; fi"' 
+								*/
+								echo 'tomcat server stopped'
+								echo 'copying the tar file from jenkins to deployment directory on app and remove the old folders and untarring the new jar and war files'
+								/* sh 'scp -rp $WORKSPACE/artifacts/artifact.tar $DEPLOYMENT_USER@$DEPOYMENT_SERVER:$DEPLOYMENT_STAGE_DIR/'
+								sh 'ssh ${USERNAME}@${HOSTNAME} "cd $DEPLOYMENT_STAGE_DIR && rm -rf *.war *.jar"'
+								sh 'ssh ${USERNAME}@${HOSTNAME} "cd $DEPLOYMENT_STAGE_DIR && tar -xvzf artifact.tar && rm -rf *.jar"'
+								sh 'ssh ${USERNAME}@${HOSTNAME} "cd $}DEPLOYMENT_DIR} && rm -rf ${ESB_WAR_FOLDERS} && cp -rp ${DEPLOYMENT_STAGE_DIR}/*.war $DEPLOYMENT_DIR"' 
+								*/
+								echo 'Deployment has been completed'
+								echo 'starting the tomcat ESB server'
+								/* sh 'ssh ${USERNAME}@${HOSTNAME} "${ESB_BIN_PATH start}"'
+								sh 'ssh ${USERNAME}@${HOSTNAME} "sleep 20"' 
+								*/
+								echo 'tomcat server started'
+							}
+						}	
 					}
 				}
 			}
@@ -167,43 +167,43 @@ spec:
 					steps {
 						container('gradle') {
 							script {
-									withMaven(maven: 'MAVEN-3.6.3') {
-										echo "I am executing Smoke Test on target dev environment post deployment"
-										/*RESP=`curl -X GET "${bamboo.uri}/RequestsRunning" -H "accept: application/xml" -H "authorization: bearer lR0AA2qfq7v9Ry96vDAgqcer1GPVd5yStmv1_aJVFS43rk06EytB7WsS0_owoiXIgpOXmZVEfkY4ST0JwHtRBk7RH0QRaldWtQT8udC0VdimdGx38RddY2sGaeeF0t9Aflr5rh1Jc_EUfkNK8YrKVxQ6kxB05aCe46CD2fkognv7TiJATmht-ycUjEsd_oy8jH5EK9fmn9eL-wXavNTQcEdsUmFm3-2r3IJDzMK7XCa74qu353yOKLvVyZ1yYQBnc1_fY5GS1BDrFLUZprxpAS30lGEu-d_JTTOQ989UJtIEB3cZzDkIQzeqdYBGCsiDdjdHo2DC1FK2kVPyBITTbQ"`
-										echo "The response for current execution status is: $RESP"
-										if [ "$RESP" != "[]" ];
-										then
-										echo "There is a test executing currently in Worksoft. Hence, not proceeding with the execution of Worksoft test cases."
-										exit 1
-										else
-										echo "There are no tests executing right now. Hence, proceeding with Worksoft test execution"
-										fi
-										# To abort the request before attempting to re-run, uncomment and run below line.
-										# abort=$(curl -X PUT -H "Authorization: Bearer $token" -d "" -H "id: ${bamboo.RequestID}" ${bamboo.uri}/Request/${bamboo.RequestID}/abort/)
-										guid=$(curl -X PUT -H "Authorization: Bearer $token" -d "" -H "parameters: {TestEnv}{${bamboo.stage_name}}" -H "id: ${bamboo.RequestID}" ${bamboo.uri}/ExecuteRequest/ | tr -d \")
-										echo "The GUID is: $guid"
-										status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/ | awk -F':' '{print $2}' | tr -d \" | tr -d \})
-										echo "The status is: $status"
-										while [[ $status != *"Completed"* ]]
-										do
-										status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/ | awk -F':' '{print $2}' | tr -d \" | tr -d \})
-										echo "The status is: $status"
-										sleep 15
-										done
-										status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/)
-										echo "The status is: $status"
-										execstatus=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/ | awk -F':' '{print $3}' | tr -d \" | tr -d \})
-										echo "The exec status is: $execstatus"
-										if [[ $execstatus != *Passed* ]];
-										then
-										echo "Failed"
-										exit 1
-										else
-										echo "Passed"
-										exit
-										fi
-										exit */
-									}
+								withMaven(maven: 'MAVEN-3.6.3') {
+									echo "I am executing Smoke Test on target dev environment post deployment"
+									/*RESP=`curl -X GET "${bamboo.uri}/RequestsRunning" -H "accept: application/xml" -H "authorization: bearer lR0AA2qfq7v9Ry96vDAgqcer1GPVd5yStmv1_aJVFS43rk06EytB7WsS0_owoiXIgpOXmZVEfkY4ST0JwHtRBk7RH0QRaldWtQT8udC0VdimdGx38RddY2sGaeeF0t9Aflr5rh1Jc_EUfkNK8YrKVxQ6kxB05aCe46CD2fkognv7TiJATmht-ycUjEsd_oy8jH5EK9fmn9eL-wXavNTQcEdsUmFm3-2r3IJDzMK7XCa74qu353yOKLvVyZ1yYQBnc1_fY5GS1BDrFLUZprxpAS30lGEu-d_JTTOQ989UJtIEB3cZzDkIQzeqdYBGCsiDdjdHo2DC1FK2kVPyBITTbQ"`
+									echo "The response for current execution status is: $RESP"
+									if [ "$RESP" != "[]" ];
+									then
+									echo "There is a test executing currently in Worksoft. Hence, not proceeding with the execution of Worksoft test cases."
+									exit 1
+									else
+									echo "There are no tests executing right now. Hence, proceeding with Worksoft test execution"
+									fi
+									# To abort the request before attempting to re-run, uncomment and run below line.
+									# abort=$(curl -X PUT -H "Authorization: Bearer $token" -d "" -H "id: ${bamboo.RequestID}" ${bamboo.uri}/Request/${bamboo.RequestID}/abort/)
+									guid=$(curl -X PUT -H "Authorization: Bearer $token" -d "" -H "parameters: {TestEnv}{${bamboo.stage_name}}" -H "id: ${bamboo.RequestID}" ${bamboo.uri}/ExecuteRequest/ | tr -d \")
+									echo "The GUID is: $guid"
+									status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/ | awk -F':' '{print $2}' | tr -d \" | tr -d \})
+									echo "The status is: $status"
+									while [[ $status != *"Completed"* ]]
+									do
+									status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/ | awk -F':' '{print $2}' | tr -d \" | tr -d \})
+									echo "The status is: $status"
+									sleep 15
+									done
+									status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/)
+									echo "The status is: $status"
+									execstatus=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/ | awk -F':' '{print $3}' | tr -d \" | tr -d \})
+									echo "The exec status is: $execstatus"
+									if [[ $execstatus != *Passed* ]];
+									then
+									echo "Failed"
+									exit 1
+									else
+									echo "Passed"
+									exit
+									fi
+									exit */
+								}
 							}
 						}
 					}
@@ -212,9 +212,9 @@ spec:
 					steps {
 						container('gradle') {
 							script {
-									withMaven(maven: 'MAVEN-3.6.3') {
-										echo 'I am running Security Test here'
-									}
+								withMaven(maven: 'MAVEN-3.6.3') {
+									echo 'I am running Security Test here'
+								}
 							}
 						}
 					}
